# Generated by Django 2.2.1 on 2019-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('book_id', models.CharField(max_length=15)),
                ('author_name', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('Student_semester', models.CharField(max_length=1)),
                ('student_id', models.CharField(max_length=20)),
                ('Father_name', models.CharField(max_length=50)),
                ('Mobile_no', models.CharField(max_length=10)),
                ('Aadhar_no', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=100)),
                ('Pin_code', models.CharField(max_length=6)),
                ('Books', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
