# Generated by Django 2.0 on 2019-07-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb1', '0003_stuent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuent',
            new_name='Student',
        ),
    ]
